/**:
  ros__parameters:
    joystick:
#      type:
      remappings:
        axes:
          linear_speed: Vertical_Left_Stick
          steering_angle: Horizontal_Right_Stick
        buttons:
          slow_mode: L1
          turbo_mode: R1
#    cmd_output:
#      type: geometry_msgs::msgs::Twist # geometry_msgs::msgs::Twist or
#      priority: 100 # [0 255]
#    cmd_range:
#      maximal_steering_angle: 0.5
#      maximal_linear_speed:
#        slow_mode: 1.0
#        turbo_mode: 2.0
